### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by jrdad1** [rafael-trevisan/apex-plugin-ig_simple_checkbox#3]
The IG region does not display when I use the plug-in. It works fine in Firefox and Chrome. My company uses IE 11 as a standard browser. I get an error in the console saying "trevis_apex_ig_simple_checkbox' is undefined". Attached is the screenshot of the console error.

![ig simple checkbox error 2018-02-22](https://user-images.githubusercontent.com/11945723/36554306-d1c76cca-17f6-11e8-858d-9dcb210d1d77.jpg)

**Comment by rafael-trevisan** [comment]
Hey @jrdad1, thanks for bringing this up.

IG Simple Checkbox has been written using [ES6](https://dev.venntro.com/2013/09/es6-part-1/) that, unfortunately, [isn't supported on IE11](https://kangax.github.io/compat-table/es6/).

I'll take a look at this to see what can be done...

**Comment by sonic0boom** [comment]
Hi Rafael, I just encountered this same issue (also with a client using IE11). I will be more than happy to buy you that beer if a fix is forthcoming! :)

**Comment by rafael-trevisan** [comment]
Did I hear 🍺 ? 😃 

I got quite busy over here...

I haven't decided yet what to do with this IE11 compatibility, but in any case (and in the meantime) I have written a special version for IE11 just for you guys.

Hope you clients enjoy it 😎 

Here is the direct link to download: https://github.com/rafael-trevisan/apex-plugin-ig_simple_checkbox/releases/download/v18.2.3/IG-Simple-Checkbox-APEX-Plugin_IE11.zip

Let me know if it works well 👍

**Comment by sonic0boom** [comment]
You, sir, have earned your beer! So far, it appears to be working without any issues. I was using a slider button in the meantime, but this is much better because the slider always displays the "off" value (i.e. "No"), and I would rather have the column blank for readability if no value is selected.

**Comment by sonic0boom** [comment]
Rafael, one question: i noticed in your demo app that the checkboxes are rendered from the start. But in my app, i have to click the field before the checkboxes show up. Is there a trick to having the empty checkbox render on page load?

**Comment by rafael-trevisan** [comment]
Hmm... the only thing I can think of is: if your IG Simple Checkbox has been set to use Y/N, and your table actually has, let's say, "Y" and <null> or "Yes" and "No", then this situation might happen. But, if you do have the same values as in IG Simple Checkbox I don't see why this would happen.

In any case, if you can't figure this out feel free to mimic your scenario on apex.oracle.com (or anywhere else you prefer) and let me know. I got quite busy over here but I'll be happy to help to troubleshoot while enjoying my 🍻 👍

**Comment by sonic0boom** [comment]
Thanks, that was the missing key. What i have is basically a copy program. The checkbox is selected for the processing step to know which records to copy based on some header detail (i have to do this since APEX$ROW_SELECTOR lacks persistence when you click on a row). As such, i just had the checkbox as an orphan IG item. Once i added it in as a pseudo column in the query (SELECT 'N' copy_flag...), the checkbox then appeared on load.

**Comment by rafael-trevisan** [comment]
Cool!

Glad you figured it out!

Have a great weekend and thanks again for the 🍻 👍

**Comment by jrdad1** [comment]
Does the IE11 solution work for the other modern browsers since I have to support all modern browsers ?

**Comment by rafael-trevisan** [comment]
Yes, it does!

The IE version supports IE besides supporting Chrome, Safari and Firefox.
